"""Правка некоторыйх отношений 1

Revision ID: 1321b1491c4a
Revises: 0b4836a5590a
Create Date: 2025-10-28 19:55:26.380260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1321b1491c4a'
down_revision: Union[str, Sequence[str], None] = '0b4836a5590a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
